# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Curl
        run: |
          response = $(curl --write-out '{%http_code}' https://www.google.com)
          if [[ response -eq 200 ]]; then
            echo "Success"
          else
            echo "Failed"
            exit 1
